Repository codestates-seb/seb40_main_017, pull requests merged in 2022-12, with the labels that each got.

#159 #52 fix: 실 서버 실행을 위한 코드 리펙토링
  server/src/main/java/team017/board/Service/BoardService.java
  server/src/main/java/team017/ord/service/OrdService.java
  server/src/main/java/team017/payment/PaymentController.java
  server/src/main/java/team017/product/Entity/Product.java
Labels: [BE] 신승현

#160 #129 fix: params seller id 삭제
  client/src/api/seller.js
Labels: [FE] 김민성

#161 Fix : 페이지네이션 정렬 조건 변경
  server/src/main/java/team017/comments/service/CommentService.java
  server/src/main/java/team017/review/service/ReviewService.java
Labels: [BE] 신지훈

#162 #52 #69 refactor: for kakao server login
  server/src/main/java/team017/member/controller/SocialController.java
  server/src/main/java/team017/member/entity/Member.java
  server/src/main/java/team017/security/jwt/service/SecurityService.java
  server/src/main/java/team017/security/oauth/service/KakaoService.java
Labels: [BE] 가빈

#163 #52 delete: 토큰 재발급 삭제
  server/src/main/java/team017/member/controller/ClientController.java
  server/src/main/java/team017/member/controller/SellerController.java
  server/src/main/java/team017/security/jwt/TokenController.java
Labels: [BE] 가빈

#165 #52 fix: 결제 API redirect url 추가
  server/src/main/java/team017/board/Service/BoardService.java
  server/src/main/java/team017/payment/PaymentController.java
Labels: [BE] 신승현

#168 #52 #69 refactor: 소셜 첫 로그인시 메일 발송 및 카카오 로그인 수정
  server/src/main/java/team017/mail/EmailServiceImpl.java
  server/src/main/java/team017/member/controller/SocialController.java
  server/src/main/java/team017/member/entity/Member.java
  server/src/main/java/team017/security/oauth/info/KakaoProfile.java
  server/src/main/java/team017/security/oauth/service/KakaoService.java
  server/src/main/resources/templates/test.html
Labels: [BE] 가빈

#169 #95 fix: 여러명 결제 시 발생하는 오류 수정
  server/src/main/java/team017/ord/entity/Ord.java
  server/src/main/java/team017/payment/KakaoPayService.java
  server/src/main/java/team017/payment/PaymentController.java
Labels: [BE] 신승현

#170 [client] 메인페이지, 주문페이지 , 수정페이지 수정
  client/src/components/HomeInfo.js
  client/src/components/HomeNav.js
  client/src/components/HomeVisual.js
  client/src/components/buyform/ClientBuyform.js
  client/src/components/buyform/PayForm.js
  client/src/components/sellerform/SellerPrice.js
  client/src/pages/payments/BuyFormPage.js
  client/src/pages/payments/CompletePage.js
  client/src/pages/sellers/SellerPatchPage.js
Labels: [BE] 신승현, [BE] 가빈, [BE] 신지훈, [FE] 권수현, [FE] 김민성, [FE] 남궁태욱

#171 Create README.md
  README.md
Labels: [BE] 신승현, [BE] 가빈, [BE] 신지훈, [FE] 권수현, [FE] 김민성, [FE] 남궁태욱

#172 "fix: totalPages 수정, sellerInfo이미지 고정, 세선정보저장"
  client/src/App.js
  client/src/features/user/userSlice.js
  client/src/pages/payments/BuyFormPage.js
  client/src/pages/sellers/SellerInfoPage.js
  client/src/pages/users/MyPage.js
Labels: [FE] 김민성

#175 fix: s 추가
  client/src/components/Pagination.js
Labels: [FE] 김민성

#176 #129 feat: 로그인 쿠키 토큰이 유효하다면 서버에 로그아웃 요청
  client/src/api/login.js
Labels: [FE] 김민성

#174 #52 메일 이미지 발송으로 수정 및 안쓰는 주석과 import 삭제
  server/src/main/java/team017/ServerApplication.java
  server/src/main/java/team017/mail/EmailService.java
  server/src/main/java/team017/mail/EmailServiceImpl.java
  server/src/main/java/team017/member/controller/ClientController.java
  server/src/main/java/team017/member/controller/MemberController.java
  server/src/main/java/team017/member/controller/SellerController.java
  server/src/main/java/team017/member/controller/SocialController.java
  server/src/main/java/team017/member/dto/MemberDto.java
  server/src/main/java/team017/member/entity/Client.java
  server/src/main/java/team017/member/entity/Member.java
  server/src/main/java/team017/member/entity/Seller.java
  server/src/main/java/team017/member/mapper/MemberMapper.java
  server/src/main/java/team017/member/repository/MemberRepository.java
  server/src/main/java/team017/security/config/SecurityConfig.java
  server/src/main/java/team017/security/jwt/TokenController.java
  server/src/main/java/team017/security/jwt/dto/LoginRequestDto.java
  server/src/main/java/team017/security/jwt/dto/TokenDto.java
  server/src/main/java/team017/security/jwt/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/team017/security/jwt/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/team017/security/jwt/refresh/RefreshToken.java
  server/src/main/java/team017/security/jwt/refresh/RefreshTokenRepository.java
  server/src/main/java/team017/security/jwt/service/MemberPrincipalService.java
  server/src/main/java/team017/security/jwt/service/SecurityService.java
  server/src/main/java/team017/security/oauth/dto/SocialPatchDto.java
  server/src/main/java/team017/security/oauth/handler/OAuth2FailureHandler.java
  server/src/main/java/team017/security/oauth/service/KakaoService.java
Labels: [BE] 가빈

#177 #52 redirect kakao
  server/src/main/java/team017/member/controller/SocialController.java
Labels: [BE] 가빈

#178 #52 refactor: 코드 주석 제거
  server/src/main/java/team017/ord/dto/OrdPostDto.java
  server/src/main/java/team017/ord/dto/OrdResponseDto.java
  server/src/main/java/team017/ord/dto/OrdSellerResponseDto.java
  server/src/main/java/team017/payment/KakaoPayService.java
  server/src/main/java/team017/payment/PaymentController.java
  server/src/main/java/team017/product/Service/ProductService.java
Labels: [BE] 신승현

#180 Fix : gradlew-wrapper.properties 수정
  server/src/main/java/team017/review/entity/Review.java
  server/src/main/java/team017/review/mapper/ReviewMapper.java
Labels: [BE] 신지훈

#182 [client] fix: 문의수정기능구현, 상품상세페이지 렌더링오류
  client/db.json
  client/public/favicon.ico
  client/public/index.html
  client/src/components/Comment.js
  client/src/components/CommentElement.js
  client/src/components/CropBoard.js
  client/src/components/Review.js
  client/src/components/TimeCheck.js
  client/src/pages/CropsListPage.js
  client/src/pages/crops/CropInfoPage.js
  client/src/pages/crops/FruitsPage.js
  client/src/pages/crops/GrainPage.js
  client/src/pages/crops/NutsPage.js
  client/src/pages/crops/VegetablePage.js
Labels: [FE] 권수현

#184 [Client] 메인, 수정페이지 카테고리 , 따옴표
  client/src/components/HomeVisual.js
  client/src/components/sellerform/SellerPrice.js
  client/src/pages/crops/GrainPage.js
  client/src/pages/sellers/SellerPatchPage.js
Labels: [FE] 남궁태욱

#186 [client] 주문 실패 페이지 버튼 메인 페이지 연결
  client/src/pages/payments/FailPage.js
Labels: [FE] 남궁태욱

#187 [client] fix: 보드중복출력 오류,구매수량 초기값1로 수정
  client/src/pages/crops/CropInfoPage.js
  client/src/pages/crops/FruitsPage.js
  client/src/pages/crops/GrainPage.js
  client/src/pages/crops/NutsPage.js
  client/src/pages/crops/VegetablePage.js
Labels: [FE] 권수현

#188 #129 feat: 소셜sns 로그인 기능구현
  client/src/App.js
  client/src/api/login.js
  client/src/pages/users/SnsLoginPage.js
Labels: [FE] 김민성

#190 fix: 주석 제거
  client/src/App.js
  client/src/api/client.js
  client/src/api/login.js
  client/src/api/seller.js
  client/src/api/signup.js
  client/src/components/Button.js
  client/src/components/Comment.js
  client/src/components/Form.js
  client/src/components/Header.js
  client/src/components/Input.js
  client/src/features/axios.js
  client/src/features/cookie.js
  client/src/features/s3.js
  client/src/features/user/userSlice.js
  client/src/pages/sellers/SellerInfoPage.js
  client/src/pages/users/LoginPage.js
  client/src/pages/users/LogoutPage.js
  client/src/pages/users/MyPage.js
  client/src/pages/users/SignupPage.js
Labels: [FE] 김민성

#191 #52 fix: 이모지 삭제
  server/src/main/java/team017/security/oauth/service/KakaoService.java
Labels: [BE] 가빈

#193 #52 refactor: 특정 주소만 허용
  server/src/main/java/team017/security/config/WebMvcConfig.java
Labels: [BE] 가빈

#192 Update README.md
  README.md
Labels: [BE] 신승현, [BE] 가빈, [BE] 신지훈, [FE] 권수현, [FE] 김민성, [FE] 남궁태욱

#196 fix: 주문 결제 페이지, 등록페이지 console 제거
  client/src/components/buyform/ClientBuyform.js
  client/src/components/buyform/PayForm.js
  client/src/components/sellerform/SellerContent.js
  client/src/pages/payments/BuyFormPage.js
  client/src/pages/payments/CompletePage.js
  client/src/pages/sellers/SellerPatchPage.js
  client/src/pages/sellers/SellerformPage.js
Labels: [FE] 남궁태욱

#202 #200 Feat : 'github actions 기능 구현'
  appspec.yml
  scripts/deploy.sh
  server/appspec.yml
  server/build.gradle
  server/src/test/java/team017/ServerApplicationTests.java
  server/src/test/java/team017/util/ApiDocumentUtils.java
Labels: [BE] 신지훈

#203 Fix : 'server.yml create -> update 로 체인지'
  server/src/main/resources/application-server.yml
Labels: [BE] 신지훈

#206 #205 Fix : 'Board content 길이 수정'
  server/src/main/java/team017/board/Entity/Board.java
  server/src/main/java/team017/board/Service/BoardService.java
  server/src/main/resources/application-server.yml
Labels: [BE] 신지훈

#207 #205 Refactor : '#52 띄어쓰기 없애기'
  server/src/main/java/team017/board/Controller/BoardController.java
  server/src/main/java/team017/board/Dto/BoardResponseDto.java
  server/src/main/java/team017/board/Dto/BoardTotalResponseDto.java
Labels: [BE] 신지훈

#208 #205 Fix : 'unicodeUser=true'
  server/src/main/resources/application-server.yml
Labels: [BE] 신지훈

#209 #52 #69 refactor : 이모지 지우기 제거 및 널값 이름 시 디폴트값 추가
  server/src/main/java/team017/security/oauth/service/KakaoService.java
Labels: [BE] 가빈

#210 #57 fix: 수량 , 가격 min 값 수정
  client/src/assets/styles/fonts/fonts.js
  client/src/components/sellerform/SellerPrice.js
  client/src/components/sellerform/SellerTitle.js
  client/src/pages/sellers/SellerPatchPage.js
Labels: [FE] 남궁태욱

#211 #205 Fix : 'comment에 member이름 가져오기'
  server/src/main/java/team017/comments/entity/Comment.java
  server/src/main/java/team017/comments/mapper/CommentMapper.java
  server/src/main/java/team017/comments/service/CommentService.java
  server/src/main/resources/application-server.yml
Labels: [BE] 신지훈

#212 #205 Fix : 'comment에 member이름 가져오기 2차수정'
  server/src/main/java/team017/comments/mapper/CommentMapper.java
Labels: [BE] 신지훈

#213 #114 feat: 판매목록 클릭시 상세페이지로 이동
  client/package-lock.json
  client/src/App.js
  client/src/pages/sellers/SellerInfoPage.js
  client/src/pages/users/MyPage.js
Labels: [FE] 김민성

#221 [client] #219 Fix: 댓글,문의 삭제가안되는오류
  client/src/components/Comment.js
  client/src/components/CommentElement.js
  client/src/components/Review.js
  client/src/components/ReviewElement.js
  client/src/components/StarRate.js
  client/src/pages/CropsListPage.js
  client/src/pages/crops/CropInfoPage.js
  client/src/pages/crops/FruitsPage.js
  client/src/pages/crops/GrainPage.js
  client/src/pages/crops/NutsPage.js
  client/src/pages/crops/VegetablePage.js
Labels: [FE] 권수현

#220 #218 feat: 주문한 사람만 리뷰 작성 가능하게 기능 추가
  server/src/main/java/team017/global/Exception/ExceptionCode.java
  server/src/main/java/team017/ord/repository/OrdRepository.java
  server/src/main/java/team017/review/service/ReviewService.java
Labels: [BE] 신승현

#223 Fix: 리뷰,문의 post 후textarea 비우기
  client/src/components/Comment.js
  client/src/components/Review.js
  client/src/pages/CropsListPage.js
  client/src/pages/crops/FruitsPage.js
  client/src/pages/crops/GrainPage.js
  client/src/pages/crops/NutsPage.js
  client/src/pages/crops/VegetablePage.js
Labels: [FE] 권수현

#224 #205 fix: 리뷰 수정
  server/src/main/java/team017/ord/repository/OrdRepository.java
  server/src/main/java/team017/review/service/ReviewService.java
Labels: [BE] 신승현

#225 #205 refactor : comment - member 연관관계 수정
  server/src/main/java/team017/comments/entity/Comment.java
  server/src/main/java/team017/member/entity/Member.java
Labels: [BE] 가빈

#227 Update README.md
  README.md
Labels: [BE] 신승현, [BE] 가빈, [BE] 신지훈, [FE] 권수현, [FE] 김민성, [FE] 남궁태욱

#231 #205 fix : 리뷰1개일 때 삭제 문제 해결
  server/src/main/java/team017/review/service/ReviewService.java
Labels: [BE] 가빈
