Repository codestates-seb/seb40_main_017, pull requests merged in 2022-11, with the labels that each got.

#9 init : application.yml 파일추가
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
Labels: [BE] 신지훈

#8 #7 client 초기설정
  client/.eslintrc.json
  client/.prettierrc.json
  client/GlobalStyles.js
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/api/.gitkeep
  client/src/assets/.gitkeep
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/Sidebar.js
  client/src/index.css
  client/src/index.js
  client/src/pages/CartPage.js
  client/src/pages/CropsListPage.js
  client/src/pages/HomePage.js
  client/src/pages/crops/CropInfoPage.js
  client/src/pages/crops/FruitsPage.js
  client/src/pages/crops/NutsPage.js
  client/src/pages/crops/RicePage.js
  client/src/pages/crops/VegiPage.js
  client/src/pages/payments/BuyFoamPage.js
  client/src/pages/payments/CompletePage.js
  client/src/pages/payments/PayPage.js
  client/src/pages/sellers/SellerInfoPage.js
  client/src/pages/sellers/SellorPostPage.js
  client/src/pages/users/LoginPage.js
  client/src/pages/users/MyPage.js
  client/src/pages/users/SignupPage.js
  client/src/reportWebVitals.js
  client/src/setupTests.js
Labels: [FE] 권수현, [FE] 김민성, [FE] 남궁태욱

#12 # 4 feat & refactor : implement and refactoring
  server/src/main/java/team017/ServerApplication.java
  server/src/main/java/team017/global/audit/Auditable.java
  server/src/main/java/team017/global/response/MultiResponseDto.java
  server/src/main/java/team017/global/response/PageInfo.java
  server/src/main/java/team017/global/response/SingleResponseDto.java
  server/src/main/java/team017/security/config/WebMvcConfig.java
Labels: [BE] 가빈

#13 #11 feat: Exception 공통 클래스 초기 구현
  server/src/main/java/team017/global/Exception/BusinessLogicException.java
  server/src/main/java/team017/global/Exception/ExceptionCode.java
Labels: [BE] 신승현

#16 #14 feat: implement member domain entities
  server/src/main/java/team017/member/entity/Client.java
  server/src/main/java/team017/member/entity/Member.java
  server/src/main/java/team017/member/entity/SellHistory.java
  server/src/main/java/team017/member/entity/Seller.java
  server/src/main/java/team017/member/entity/SellerImage.java
Labels: [BE] 가빈

#17 add build.gradle +h2
  server/build.gradle
  server/src/main/java/team017/response/MultiResponseDto.java
  server/src/main/java/team017/response/PageInfo.java
  server/src/main/java/team017/response/SingleResponseDto.java
Labels: [BE] 신지훈

#20 #15 #19 feat: 초기 기능 구현
  server/src/main/java/team017/board/Controller/BoardController.java
  server/src/main/java/team017/board/Dto/BoardPatchDto.java
  server/src/main/java/team017/board/Dto/BoardPostDto.java
  server/src/main/java/team017/board/Dto/BoardResponseDto.java
  server/src/main/java/team017/board/Entity/Board.java
  server/src/main/java/team017/board/Mapper/BoardMapper.java
  server/src/main/java/team017/board/Repository/BoardRepository.java
  server/src/main/java/team017/board/Service/BoardService.java
  server/src/main/java/team017/product/Controller/ProductController.java
  server/src/main/java/team017/product/Dto/ProductPatchDto.java
  server/src/main/java/team017/product/Dto/ProductPostDto.java
  server/src/main/java/team017/product/Dto/ProductResponseDto.java
  server/src/main/java/team017/product/Entity/Product.java
  server/src/main/java/team017/product/Mapper/ProductMapper.java
  server/src/main/java/team017/product/Repository/ProductRepository.java
  server/src/main/java/team017/product/Service/ProductService.java
  server/src/main/java/team017/response/MultiResponseDto.java
  server/src/main/java/team017/response/PageInfo.java
  server/src/main/java/team017/response/SingleResponseDto.java
Labels: [BE] 신승현

#22 #18 feat: implement dto validation
  server/build.gradle
  server/src/main/java/team017/member/controller/MemberController.java
  server/src/main/java/team017/member/dto/MemberDto.java
  server/src/main/java/team017/member/repository/MemberRepository.java
  server/src/main/java/team017/member/service/MemberService.java
Labels: [BE] 가빈

#23 #21 feat : Ord초기 기능 구현
  server/src/main/java/team017/ord/controller/OrdController.java
  server/src/main/java/team017/ord/dto/OrdDto.java
  server/src/main/java/team017/ord/entity/Ord.java
  server/src/main/java/team017/ord/repository/OrdRepository.java
  server/src/main/java/team017/ord/service/OrdService.java
Labels: [BE] 신지훈

#26 #18 feat: signup and delete member
  server/build.gradle
  server/src/main/java/team017/global/Exception/ExceptionCode.java
  server/src/main/java/team017/member/controller/MemberController.java
  server/src/main/java/team017/member/dto/MemberDto.java
  server/src/main/java/team017/member/mapper/MemberMapper.java
  server/src/main/java/team017/member/service/MemberService.java
  server/src/main/java/team017/ord/entity/Ord.java
Labels: [BE] 가빈

#28 #27 feat : 연관관계 매핑
  server/src/main/java/team017/member/controller/MemberController.java
  server/src/main/java/team017/member/dto/MemberDto.java
  server/src/main/java/team017/member/entity/Client.java
  server/src/main/java/team017/member/entity/Member.java
  server/src/main/java/team017/member/entity/SellHistory.java
  server/src/main/java/team017/member/entity/Seller.java
  server/src/main/java/team017/member/entity/SellerImage.java
Labels: [BE] 가빈

#29 init: mysql 설정
  server/.gitignore
  server/build.gradle
  server/src/main/java/team017/ServerApplication.java
  server/src/main/java/team017/board/Controller/BoardController.java
  server/src/main/java/team017/board/Dto/BoardPostDto.java
  server/src/main/java/team017/board/Entity/Board.java
  server/src/main/java/team017/board/Service/BoardService.java
  server/src/main/java/team017/product/Entity/Product.java
  server/src/main/resources/application.yml
Labels: [BE] 신승현

#32 #31 feat : 이미지삽입기능구현
  server/build.gradle
  server/src/main/generated/team017/member/mapper/MemberMapperImpl.java
  server/src/main/java/team017/ServerApplication.java
  server/src/main/java/team017/image/FileUploadController.java
  server/src/main/java/team017/image/S3Config.java
  server/src/main/java/team017/image/S3Uploader.java
  server/src/main/java/team017/member/dto/MemberDto.java
  server/src/main/java/team017/review/controller/ReviewController.java
  server/src/main/java/team017/review/dto/ReviewDto.java
  server/src/main/java/team017/review/entity/Review.java
  server/src/main/java/team017/review/repository/ReviewRepository.java
  server/src/main/java/team017/review/service/ReviewService.java
  server/src/main/java/team017/security/config/WebMvcConfig.java
  server/src/main/resources/application.yml
Labels: [BE] 신지훈

#35 feat & fix : 에러 수정 및 마이페이지 구현
  server/build.gradle
  server/src/main/generated/team017/member/mapper/MemberMapperImpl.java
  server/src/main/java/team017/ServerApplication.java
  server/src/main/java/team017/board/Entity/Board.java
  server/src/main/java/team017/member/controller/ClientController.java
  server/src/main/java/team017/member/controller/MemberController.java
  server/src/main/java/team017/member/controller/SellerController.java
  server/src/main/java/team017/member/dto/MemberDto.java
  server/src/main/java/team017/member/entity/Member.java
  server/src/main/java/team017/member/mapper/MemberMapper.java
  server/src/main/java/team017/member/repository/ClientRepository.java
  server/src/main/java/team017/member/repository/SellerRepository.java
  server/src/main/java/team017/member/service/ClientService.java
  server/src/main/java/team017/member/service/MemberService.java
  server/src/main/java/team017/member/service/SellerService.java
  server/src/main/java/team017/product/Entity/Product.java
  server/src/main/java/team017/security/config/SecurityConfig.java
  server/src/main/java/team017/security/config/WebMvcConfig.java
  server/src/main/java/team017/security/utils/CustomAuthorityUtils.java
Labels: [BE] 가빈

#36 #15 #19 feat: create 기능 구현
  server/.gitignore
  server/src/main/java/team017/board/Controller/BoardController.java
  server/src/main/java/team017/board/Dto/BoardPostDto.java
  server/src/main/java/team017/board/Dto/BoardResponseDto.java
  server/src/main/java/team017/board/Entity/Board.java
  server/src/main/java/team017/board/Mapper/BoardMapper.java
  server/src/main/java/team017/board/Repository/BoardRepository.java
  server/src/main/java/team017/board/Service/BoardService.java
  server/src/main/java/team017/member/entity/Seller.java
  server/src/main/java/team017/product/Entity/Product.java
  server/src/main/java/team017/product/Mapper/ProductMapper.java
  server/src/main/java/team017/product/Repository/ProductRepository.java
  server/src/main/resources/application.yml
Labels: [BE] 신승현

#42 #41 feat: mapping entities
  server/src/main/java/team017/board/Entity/Board.java
  server/src/main/java/team017/member/controller/SellerController.java
  server/src/main/java/team017/member/entity/Client.java
  server/src/main/java/team017/member/entity/Seller.java
  server/src/main/java/team017/member/service/SellerService.java
  server/src/main/java/team017/ord/entity/Ord.java
  server/src/main/java/team017/product/Entity/Product.java
  server/src/main/java/team017/review/entity/Review.java
Labels: [BE] 신승현, [BE] 가빈, [BE] 신지훈

#45 # 44 feat: 회원 수정 구현
  server/src/main/java/team017/member/controller/ClientController.java
  server/src/main/java/team017/member/controller/SellerController.java
  server/src/main/java/team017/member/dto/ClientPatchDto.java
  server/src/main/java/team017/member/dto/SellerPatchDto.java
  server/src/main/java/team017/member/entity/Seller.java
  server/src/main/java/team017/member/mapper/MemberMapper.java
  server/src/main/java/team017/member/service/MemberService.java
  server/src/main/java/team017/member/service/SellerService.java
Labels: [BE] 가빈

#51 #43 feat: 상품, 판매 게시글 create 기능 구현 완료
  server/src/main/java/team017/board/Controller/BoardController.java
  server/src/main/java/team017/board/Mapper/BoardMapper.java
  server/src/main/java/team017/board/Service/BoardService.java
  server/src/main/java/team017/global/Exception/ExceptionCode.java
  server/src/main/java/team017/product/Mapper/ProductMapper.java
  server/src/main/java/team017/product/Repository/ProductRepository.java
  server/src/main/java/team017/product/Service/ProductService.java
Labels: [BE] 신승현

#53 refactor: 예외 메세지 출력 및 회원 코드 리펙터링
  server/src/main/java/team017/global/error/ConstraintViolationError.java
  server/src/main/java/team017/global/error/ErrorResponse.java
  server/src/main/java/team017/global/error/FieldError.java
  server/src/main/java/team017/global/error/GlobalExceptionAdvice.java
  server/src/main/java/team017/member/controller/ClientController.java
  server/src/main/java/team017/member/controller/MemberController.java
  server/src/main/java/team017/member/controller/SellerController.java
  server/src/main/java/team017/member/service/ClientService.java
  server/src/main/java/team017/member/service/MemberService.java
  server/src/main/java/team017/member/service/SellerService.java
Labels: [BE] 가빈

#54 #43 feat: 판매 게시글, 상품 update, delete 기능 구현
  server/src/main/java/team017/board/Controller/BoardController.java
  server/src/main/java/team017/board/Dto/BoardPatchDto.java
  server/src/main/java/team017/board/Dto/BoardPostDto.java
  server/src/main/java/team017/board/Service/BoardService.java
  server/src/main/java/team017/global/Exception/ExceptionCode.java
  server/src/main/java/team017/product/Mapper/ProductMapper.java
  server/src/main/java/team017/product/Repository/ProductRepository.java
Labels: [BE] 신승현

#55 #43 feat: 판매 게시판- 특정 상품 조회 기능 구현 완료 + 조회수 기능 추가
  server/src/main/java/team017/board/Controller/BoardController.java
  server/src/main/java/team017/board/Dto/BoardResponseDto.java
  server/src/main/java/team017/board/Entity/Board.java
  server/src/main/java/team017/board/Mapper/BoardMapper.java
  server/src/main/java/team017/board/Service/BoardService.java
Labels: [BE] 신승현

#56 #47: feat: 메인페이지 구현
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/HomeInfo.js
  client/src/components/HomeLayout.js
  client/src/components/HomeNav.js
  client/src/components/HomeVisual.js
  client/src/index.js
  client/src/pages/HomePage.js
Labels: [FE] 남궁태욱

#58 PR 중간 저장
  server/src/main/java/team017/board/Controller/BoardController.java
  server/src/main/java/team017/board/Repository/BoardRepository.java
  server/src/main/java/team017/board/Service/BoardService.java
Labels: [BE] 신승현

#60 #59 feat : jwt 관련 기능 구현 및 핸들러 커스텀
  server/build.gradle
  server/src/main/java/team017/global/Exception/ExceptionCode.java
  server/src/main/java/team017/member/controller/ClientController.java
  server/src/main/java/team017/member/controller/SellerController.java
  server/src/main/java/team017/member/dto/MemberDto.java
  server/src/main/java/team017/member/entity/Member.java
  server/src/main/java/team017/member/mapper/MemberMapper.java
  server/src/main/java/team017/member/service/ClientService.java
  server/src/main/java/team017/member/service/SellerService.java
  server/src/main/java/team017/security/filter/JwtFilter.java
  server/src/main/java/team017/security/handler/MemberAccessDeniedHandler.java
  server/src/main/java/team017/security/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/team017/security/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/team017/security/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/team017/security/jwt/JwtProvider.java
  server/src/main/java/team017/security/jwt/TokenDto.java
  server/src/main/java/team017/security/service/MemberDetail.java
  server/src/main/java/team017/security/service/MemberDetailService.java
  server/src/main/resources/application.yml
  server/src/test/java/team017/ServerApplicationTests.java
  server/src/test/java/team017/member/ClientControllerTest.java
  server/src/test/java/team017/member/MemberControllerTest.java
Labels: [BE] 가빈

#62 #61 feat : 게시판 댓글 기능 구현
  server/src/main/generated/team017/board/Mapper/BoardMapperImpl.java
  server/src/main/generated/team017/member/mapper/MemberMapperImpl.java
  server/src/main/generated/team017/product/Mapper/ProductMapperImpl.java
  server/src/main/java/team017/ServerApplication.java
  server/src/main/java/team017/board/Controller/BoardController.java
  server/src/main/java/team017/board/Service/BoardService.java
  server/src/main/java/team017/comments/controller/CommentController.java
  server/src/main/java/team017/comments/dto/CommentPatchDto.java
  server/src/main/java/team017/comments/dto/CommentPostDto.java
  server/src/main/java/team017/comments/dto/CommentResponseDto.java
  server/src/main/java/team017/comments/entity/Comment.java
  server/src/main/java/team017/comments/mapper/CommentMapper.java
  server/src/main/java/team017/comments/repository/CommentRepository.java
  server/src/main/java/team017/comments/service/CommentService.java
  server/src/main/java/team017/global/Exception/ExceptionCode.java
  server/src/main/java/team017/global/audit/Auditable.java
  server/src/main/java/team017/global/error/GlobalExceptionAdvice.java
  server/src/main/java/team017/global/response/SingleResponseDto.java
  server/src/main/java/team017/member/service/MemberService.java
  server/src/main/java/team017/ord/dto/OrdPatchDto.java
  server/src/main/java/team017/ord/dto/OrdPostDto.java
  server/src/main/java/team017/ord/dto/OrdResponseDto.java
  server/src/main/java/team017/ord/entity/Ord.java
  server/src/main/java/team017/ord/service/OrdService.java
  server/src/main/resources/application.yml
  server/src/test/java/team017/ServerApplicationTests.java
Labels: [BE] 신지훈

#63 #43 feat: 판매글 전체 조회 기능 + 카테고리 별 조회 기능 구현 완료
  server/src/main/java/team017/board/Controller/BoardController.java
  server/src/main/java/team017/board/Dto/BoardTotalResponseDto.java
  server/src/main/java/team017/board/Entity/Board.java
  server/src/main/java/team017/board/Mapper/BoardMapper.java
  server/src/main/java/team017/board/Repository/BoardRepository.java
  server/src/main/java/team017/board/Service/BoardService.java
  server/src/main/java/team017/global/response/MultiResponseDto.java
  server/src/main/java/team017/security/jwt/JwtProvider.java
Labels: [BE] 신승현

#65 #52 refactor: Board + Product code refactor
  server/src/main/java/team017/board/Dto/BoardPatchDto.java
  server/src/main/java/team017/board/Dto/BoardPostDto.java
  server/src/main/java/team017/board/Dto/BoardResponseDto.java
  server/src/main/java/team017/board/Dto/BoardTotalResponseDto.java
  server/src/main/java/team017/board/Service/BoardService.java
  server/src/main/java/team017/product/Controller/ProductController.java
  server/src/main/java/team017/product/Dto/ProductPatchDto.java
  server/src/main/java/team017/product/Dto/ProductPostDto.java
  server/src/main/java/team017/product/Dto/ProductResponseDto.java
  server/src/main/java/team017/product/Entity/Product.java
  server/src/main/java/team017/product/Mapper/ProductMapper.java
  server/src/main/java/team017/product/Service/ProductService.java
Labels: [BE] 신승현

#67 #48 feat:로그인&회원가입입css & 1차기능, 유효성검사, 헤더css& 기능
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Button.js
  client/src/components/Container.js
  client/src/components/Form.js
  client/src/components/Header.js
  client/src/components/Input.js
  client/src/features/cookie.js
  client/src/features/user/userSlice.js
  client/src/pages/HomePage.js
  client/src/pages/users/LoginPage.js
  client/src/pages/users/LogoutPage.js
  client/src/pages/users/SignupPage.js
Labels: [FE] 김민성

#72 feat : 로그인 1차 구현
  server/src/main/java/team017/global/error/GlobalExceptionAdvice.java
  server/src/main/java/team017/member/entity/Member.java
  server/src/main/java/team017/member/entity/ProviderType.java
  server/src/main/java/team017/member/entity/Seller.java
  server/src/main/java/team017/member/entity/SellerImage.java
  server/src/main/java/team017/member/repository/MemberRepository.java
  server/src/main/java/team017/member/service/MemberService.java
  server/src/main/java/team017/security/auth/AuthToken.java
  server/src/main/java/team017/security/auth/AuthTokenProvider.java
  server/src/main/java/team017/security/auth/CustomOAuth2Service.java
  server/src/main/java/team017/security/auth/JwtConfig.java
  server/src/main/java/team017/security/auth/MemberPrincipal.java
  server/src/main/java/team017/security/auth/MemberPrincipalService.java
  server/src/main/java/team017/security/auth/OAuth2UserInfo.java
  server/src/main/java/team017/security/auth/OAuth2UserInfoFactory.java
  server/src/main/java/team017/security/auth/TokenAuthenticationFilter.java
  server/src/main/java/team017/security/config/SecurityConfig.java
  server/src/main/java/team017/security/jwt/AuthController.java
  server/src/main/java/team017/security/jwt/JwtFilter.java
  server/src/main/java/team017/security/jwt/JwtProvider.java
  server/src/main/java/team017/security/jwt/JwtSecurityConfig.java
  server/src/main/java/team017/security/jwt/MemberDetail.java
  server/src/main/java/team017/security/jwt/MemberDetailService.java
  server/src/main/java/team017/security/jwt/dto/LoginDto.java
  server/src/main/java/team017/security/jwt/dto/TokenDto.java
  server/src/main/java/team017/security/jwt/dto/TokenRequestDto.java
  server/src/main/java/team017/security/refresh/RefreshToken.java
  server/src/main/java/team017/security/refresh/RefreshTokenRepository.java
  server/src/main/java/team017/security/service/AuthService.java
  server/src/main/java/team017/security/service/MemberDetailService.java
  server/src/main/java/team017/security/utils/SecurityUtil.java
  server/src/main/resources/application.yml
Labels: [BE] 가빈

#73 # 69 feat : 로그인 2차 구현
  server/src/main/java/team017/ServerApplication.java
  server/src/main/java/team017/global/error/GlobalExceptionAdvice.java
  server/src/main/java/team017/member/entity/Member.java
  server/src/main/java/team017/member/service/MemberService.java
  server/src/main/java/team017/security/auth/AuthController.java
  server/src/main/java/team017/security/auth/AuthToken.java
  server/src/main/java/team017/security/auth/AuthTokenProvider.java
  server/src/main/java/team017/security/auth/CustomOAuth2Service.java
  server/src/main/java/team017/security/auth/JwtConfig.java
  server/src/main/java/team017/security/auth/KakaoUserInfo.java
  server/src/main/java/team017/security/auth/OAuth2UserInfo.java
  server/src/main/java/team017/security/auth/OAuth2UserInfoFactory.java
  server/src/main/java/team017/security/auth/help/ApiResponse.java
  server/src/main/java/team017/security/auth/help/ApiResponseHeader.java
  server/src/main/java/team017/security/auth/help/AuthReqModel.java
  server/src/main/java/team017/security/config/AppProperties.java
  server/src/main/java/team017/security/config/JwtSecurityConfig.java
  server/src/main/java/team017/security/config/SecurityConfig.java
  server/src/main/java/team017/security/handler/OAuth2FailureHandler.java
  server/src/main/java/team017/security/handler/OAuth2SuccessHandler.java
  server/src/main/java/team017/security/jwt/AuthController.java
  server/src/main/java/team017/security/jwt/JwtController.java
  server/src/main/java/team017/security/jwt/JwtFilter.java
  server/src/main/java/team017/security/jwt/JwtProvider.java
  server/src/main/java/team017/security/jwt/JwtService.java
  server/src/main/java/team017/security/jwt/LoginMapper.java
  server/src/main/java/team017/security/jwt/dto/LoginDto.java
  server/src/main/java/team017/security/jwt/dto/LoginResponse.java
  server/src/main/java/team017/security/refresh/RefreshToken.java
  server/src/main/java/team017/security/refresh/RefreshTokenRepository.java
  server/src/main/java/team017/security/utils/CookieUtil.java
  server/src/main/resources/application.yml
Labels: [BE] 가빈

#74 add: Spring Rest Docs Board 추가
  server/src/docs/index.adoc
  server/src/test/java/team017/Board/BoardControllerTest.java
  server/src/test/java/team017/util/ApiDocumentUtils.java
Labels: [BE] 신승현

#75 docs: member rest docs
  server/src/docs/member.adoc
  server/src/test/java/team017/Board/BoardControllerTest.java
  server/src/test/java/team017/member/ClientControllerTest.java
  server/src/test/java/team017/member/MemberControllerTest.java
Labels: documentation, [BE] 가빈

#76 #50 feat:게시판 페이지, 푸터, 판매물품상세페이지 UI 구현
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/assets/styles/GlobalStyles.js
  client/src/assets/styles/img/CropDetail.png
  client/src/assets/styles/img/farmer.jpeg
  client/src/assets/styles/img/lettuce.jpg
  client/src/components/CropCard.js
  client/src/components/CropListPageUI.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/StarRate.js
  client/src/components/data.js
  client/src/pages/crops/CropInfoPage.js
Labels: [FE] 권수현

#78 #69 refactor : 로그인 3차..
  server/src/main/java/team017/global/Exception/ExceptionCode.java
  server/src/main/java/team017/member/dto/MemberDto.java
  server/src/main/java/team017/member/dto/SellerPatchDto.java
  server/src/main/java/team017/member/entity/Member.java
  server/src/main/java/team017/member/entity/Seller.java
  server/src/main/java/team017/member/service/MemberService.java
  server/src/main/java/team017/member/service/SellerService.java
  server/src/main/java/team017/security/auth/MemberPrincipal.java
  server/src/main/java/team017/security/config/JwtSecurityConfig.java
  server/src/main/java/team017/security/config/SecurityConfig.java
  server/src/main/java/team017/security/dto/LoginRequestDto.java
  server/src/main/java/team017/security/dto/LoginResponse.java
  server/src/main/java/team017/security/dto/TokenDto.java
  server/src/main/java/team017/security/dto/TokenRequestDto.java
  server/src/main/java/team017/security/jwt/JwtController.java
  server/src/main/java/team017/security/jwt/JwtFilter.java
  server/src/main/java/team017/security/jwt/JwtProvider.java
  server/src/main/java/team017/security/jwt/JwtService.java
  server/src/main/java/team017/security/jwt/LoginMapper.java
  server/src/main/java/team017/security/jwt/dto/LoginDto.java
  server/src/main/java/team017/security/provider/LoginMapper.java
  server/src/main/java/team017/security/provider/SecurityController.java
  server/src/main/java/team017/security/provider/SecurityFilter.java
  server/src/main/java/team017/security/provider/SecurityProvider.java
  server/src/main/java/team017/security/provider/SecurityService.java
  server/src/main/java/team017/security/provider/service/MemberDetail.java
  server/src/main/java/team017/security/provider/service/MemberDetailService.java
  server/src/main/java/team017/security/refresh/RefreshToken.java
  server/src/main/java/team017/security/refresh/RefreshTokenRepository.java
  server/src/main/java/team017/security/utils/CustomAuthorityUtils.java
Labels: [BE] 가빈

#79 #64 feat: 판매 게시글에서 이미지 불러오기 기능 구현
  server/src/main/java/team017/board/Dto/BoardPatchDto.java
  server/src/main/java/team017/board/Dto/BoardPostDto.java
  server/src/main/java/team017/board/Dto/BoardResponseDto.java
  server/src/main/java/team017/board/Dto/BoardTotalResponseDto.java
  server/src/main/java/team017/board/Entity/Board.java
  server/src/main/java/team017/image/Entity/Image.java
  server/src/main/java/team017/image/Repository/ImageRepository.java
  server/src/main/java/team017/product/Entity/Product.java
  server/src/main/java/team017/product/Service/ProductService.java
Labels: [BE] 신승현

#81 #69 refactor : 클래스 병합
  server/src/main/java/team017/ServerApplication.java
  server/src/main/java/team017/member/entity/Member.java
  server/src/main/java/team017/security/auth/AuthController.java
  server/src/main/java/team017/security/auth/AuthToken.java
  server/src/main/java/team017/security/auth/AuthTokenProvider.java
  server/src/main/java/team017/security/auth/CustomOAuth2Service.java
  server/src/main/java/team017/security/auth/JwtConfig.java
  server/src/main/java/team017/security/auth/KakaoUserInfo.java
  server/src/main/java/team017/security/auth/MemberPrincipalService.java
  server/src/main/java/team017/security/auth/OAuth2UserInfo.java
  server/src/main/java/team017/security/auth/OAuth2UserInfoFactory.java
  server/src/main/java/team017/security/auth/TokenAuthenticationFilter.java
  server/src/main/java/team017/security/auth/help/ApiResponse.java
  server/src/main/java/team017/security/auth/help/ApiResponseHeader.java
  server/src/main/java/team017/security/auth/help/AuthReqModel.java
  server/src/main/java/team017/security/config/AppProperties.java
  server/src/main/java/team017/security/config/JwtSecurityConfig.java
  server/src/main/java/team017/security/config/SecurityConfig.java
  server/src/main/java/team017/security/config/WebMvcConfig.java
  server/src/main/java/team017/security/controller/SecurityController.java
  server/src/main/java/team017/security/dto/LoginMapper.java
  server/src/main/java/team017/security/filter/SecurityFilter.java
  server/src/main/java/team017/security/handler/OAuth2FailureHandler.java
  server/src/main/java/team017/security/handler/OAuth2SuccessHandler.java
  server/src/main/java/team017/security/info/KakaoUserInfo.java
  server/src/main/java/team017/security/info/OAuth2UserInfo.java
  server/src/main/java/team017/security/info/OAuth2UserInfoFactory.java
  server/src/main/java/team017/security/provider/SecurityController.java
  server/src/main/java/team017/security/provider/SecurityProvider.java
  server/src/main/java/team017/security/provider/service/MemberDetail.java
  server/src/main/java/team017/security/provider/service/MemberDetailService.java
  server/src/main/java/team017/security/service/CustomOAuth2Service.java
  server/src/main/java/team017/security/service/MemberPrincipal.java
  server/src/main/java/team017/security/service/MemberPrincipalService.java
  server/src/main/java/team017/security/service/SecurityService.java
  server/src/main/java/team017/security/utils/CustomAuthorityUtils.java
  server/src/main/resources/application.yml
Labels: [BE] 가빈

#83 #33 fix : Review 기능 고치기
  server/build.gradle
  server/src/main/java/team017/board/Entity/Board.java
  server/src/main/java/team017/comments/entity/Comment.java
  server/src/main/java/team017/comments/service/CommentService.java
  server/src/main/java/team017/global/Exception/ExceptionCode.java
  server/src/main/java/team017/image/S3Uploader.java
  server/src/main/java/team017/member/entity/Member.java
  server/src/main/java/team017/ord/dto/OrdPatchDto.java
  server/src/main/java/team017/ord/dto/OrdPostDto.java
  server/src/main/java/team017/ord/dto/OrdResponseDto.java
  server/src/main/java/team017/ord/entity/Ord.java
  server/src/main/java/team017/ord/mapper/OrdMapper.java
  server/src/main/java/team017/ord/service/OrdService.java
  server/src/main/java/team017/review/controller/ReviewController.java
  server/src/main/java/team017/review/dto/ReviewPostDto.java
  server/src/main/java/team017/review/dto/ReviewResponseDto.java
  server/src/main/java/team017/review/entity/Review.java
  server/src/main/java/team017/review/mapper/ReviewMapper.java
  server/src/main/java/team017/review/service/ReviewService.java
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
  server/src/test/java/team017/member/ClientControllerTest.java
  server/src/test/java/team017/member/MemberControllerTest.java
Labels: [BE] 신지훈

#86 #66 #85 feat: 판매 게시글 별점 기능 + 판매자 마이페이지 기능 구현 완료
  server/src/main/generated/team017/board/Mapper/BoardMapperImpl.java
  server/src/main/java/team017/board/Controller/BoardController.java
  server/src/main/java/team017/board/Dto/BoardForSellerMyPageDto.java
  server/src/main/java/team017/board/Dto/BoardPatchDto.java
  server/src/main/java/team017/board/Dto/BoardPostDto.java
  server/src/main/java/team017/board/Dto/BoardResponseDto.java
  server/src/main/java/team017/board/Dto/BoardTotalResponseDto.java
  server/src/main/java/team017/board/Entity/Board.java
  server/src/main/java/team017/board/Mapper/BoardMapper.java
  server/src/main/java/team017/board/Repository/BoardRepository.java
  server/src/main/java/team017/board/Service/BoardService.java
  server/src/main/java/team017/global/response/MultiSellerResponseDto.java
  server/src/main/java/team017/image/Entity/Image.java
  server/src/main/java/team017/member/controller/SellerController.java
  server/src/main/java/team017/member/service/SellerService.java
  server/src/main/java/team017/product/Entity/Product.java
  server/src/main/java/team017/review/entity/Review.java
  server/src/main/java/team017/review/repository/ReviewRepository.java
  server/src/main/java/team017/review/service/ReviewService.java
Labels: [BE] 신승현

#87 # 33 Fix : Comment, Review 게시판별 조회 기능 수정
  server/src/main/java/team017/board/Entity/Board.java
  server/src/main/java/team017/comments/controller/CommentController.java
  server/src/main/java/team017/comments/repository/CommentRepository.java
  server/src/main/java/team017/comments/service/CommentService.java
  server/src/main/java/team017/review/controller/ReviewController.java
  server/src/main/java/team017/review/repository/ReviewRepository.java
  server/src/main/java/team017/review/service/ReviewService.java
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
Labels: [BE] 신지훈

#89 fix: conflict 수정
  server/src/main/java/team017/board/Entity/Board.java
  server/src/main/java/team017/board/Mapper/BoardMapper.java
  server/src/main/java/team017/board/Repository/BoardRepository.java
  server/src/main/java/team017/image/Repository/ImageRepository.java
  server/src/main/java/team017/product/Mapper/ProductMapper.java
  server/src/main/java/team017/product/Repository/ProductRepository.java
  server/src/main/java/team017/product/Service/ProductService.java
  server/src/main/java/team017/review/service/ReviewService.java
Labels: [BE] 신승현

#90 fix: fix response
  server/src/main/java/team017/global/Exception/ExceptionCode.java
  server/src/main/java/team017/security/controller/SecurityController.java
  server/src/main/java/team017/security/dto/LoginMapper.java
  server/src/main/java/team017/security/dto/LoginResponse.java
Labels: [BE] 가빈

#91 #69 # 52 refactor : 로그인 응답 코드 및 헤더 리팩터링
  server/src/main/java/team017/security/controller/SecurityController.java
  server/src/main/java/team017/security/dto/LoginMapper.java
  server/src/main/java/team017/security/service/SecurityService.java
Labels: [BE] 가빈

#92 #69 카카오 로그인 수정
  server/build.gradle
  server/src/main/java/team017/member/entity/Member.java
  server/src/main/java/team017/member/service/MemberService.java
  server/src/main/java/team017/security/config/SecurityConfig.java
  server/src/main/java/team017/security/controller/SecurityController.java
  server/src/main/java/team017/security/controller/SocialController.java
  server/src/main/java/team017/security/dto/KakaoToken.java
  server/src/main/java/team017/security/handler/OAuth2SuccessHandler.java
  server/src/main/java/team017/security/info/KakaoProfile.java
  server/src/main/java/team017/security/jwt/JwtToken.java
  server/src/main/java/team017/security/provider/SecurityProvider.java
  server/src/main/java/team017/security/service/KakaoService.java
  server/src/main/java/team017/security/service/SecurityService.java
  server/src/main/java/team017/security/utils/CustomAuthorityUtils.java
  server/src/main/resources/templates/test.html
Labels: [BE] 가빈

#93 #21 Feat : Order 기능 조..금..구..현
  server/src/main/java/team017/ord/controller/OrdController.java
  server/src/main/java/team017/ord/dto/OrdPatchDto.java
  server/src/main/java/team017/ord/dto/OrdPostDto.java
  server/src/main/java/team017/ord/dto/OrdResponseDto.java
  server/src/main/java/team017/ord/dto/OrdSimpleResponseDto.java
  server/src/main/java/team017/ord/entity/Ord.java
  server/src/main/java/team017/ord/mapper/OrdMapper.java
  server/src/main/java/team017/ord/service/OrdService.java
  server/src/main/java/team017/product/Entity/Product.java
  server/src/main/java/team017/review/service/ReviewService.java
Labels: [BE] 신지훈

#94 #52 fix: fix ord domain
  server/src/main/java/team017/ord/controller/OrdController.java
  server/src/main/java/team017/ord/dto/OrdPostDto.java
  server/src/main/java/team017/ord/entity/Ord.java
  server/src/main/java/team017/ord/mapper/OrdMapper.java
  server/src/main/java/team017/ord/service/OrdService.java
Labels: [BE] 가빈

#96 #95 feat: 목업 데이터 기반 결제 테스트 진행
  server/src/main/java/team017/ord/service/OrdService.java
  server/src/main/java/team017/payment/Amount.java
  server/src/main/java/team017/payment/ApproveResponseDto.java
  server/src/main/java/team017/payment/KakaoPayService.java
  server/src/main/java/team017/payment/PaymentController.java
  server/src/main/java/team017/payment/ReadyResponseDto.java
Labels: [BE] 신승현

#97 #52 #69 #95 refactor & feat : 소셜 로그인 수정 및 카카오 페이 결제 구현
  server/src/main/java/team017/kakaopay/Amount.java
  server/src/main/java/team017/kakaopay/ApproveResponse.java
  server/src/main/java/team017/kakaopay/KakaopayController.java
  server/src/main/java/team017/kakaopay/KakaopayService.java
  server/src/main/java/team017/kakaopay/Payment.java
  server/src/main/java/team017/kakaopay/ReadyResponse.java
  server/src/main/java/team017/product/Service/ProductService.java
  server/src/main/java/team017/security/config/SecurityConfig.java
  server/src/main/java/team017/security/config/WebMvcConfig.java
  server/src/main/java/team017/security/controller/SecurityController.java
  server/src/main/java/team017/security/controller/SocialController.java
  server/src/main/java/team017/security/dto/SocialPatchDto.java
  server/src/main/java/team017/security/service/KakaoService.java
  server/src/main/java/team017/security/service/SecurityService.java
  server/src/main/resources/application.yml
  server/src/main/resources/static/images/kakao_login_medium_narrow.png
Labels: [BE] 가빈

#98 #21 #95 feat: 실제 주문 내역 기반 결제 기능 구현 완료+ fix: order post 기능 수정
  server/src/main/java/team017/ord/controller/OrdController.java
  server/src/main/java/team017/ord/dto/OrdPostDto.java
  server/src/main/java/team017/ord/dto/OrdResponseDto.java
  server/src/main/java/team017/ord/entity/Ord.java
  server/src/main/java/team017/ord/mapper/OrdMapper.java
  server/src/main/java/team017/payment/Amount.java
  server/src/main/java/team017/payment/ApproveResponseDto.java
  server/src/main/java/team017/payment/KakaoPayService.java
  server/src/main/java/team017/payment/PaymentController.java
  server/src/main/java/team017/payment/ReadyResponseDto.java
Labels: [BE] 신승현

#100 #52 refactor : refactoring pay and login
  server/src/main/java/team017/kakaopay/Amount.java
  server/src/main/java/team017/kakaopay/ApproveResponse.java
  server/src/main/java/team017/kakaopay/KakaopayController.java
  server/src/main/java/team017/kakaopay/KakaopayService.java
  server/src/main/java/team017/kakaopay/Payment.java
  server/src/main/java/team017/kakaopay/ReadyResponse.java
  server/src/main/java/team017/pay/KakaoPayApproveDto.java
  server/src/main/java/team017/pay/KakaoPayRequestDto.java
  server/src/main/java/team017/pay/PayController.java
  server/src/main/java/team017/pay/PayDto.java
  server/src/main/java/team017/pay/PayService.java
  server/src/main/java/team017/payment/KakaoPayService.java
  server/src/main/java/team017/payment/PaymentController.java
  server/src/main/java/team017/security/controller/SecurityController.java
  server/src/main/java/team017/security/service/SecurityService.java
Labels: [BE] 가빈

#103 #102 [client] 사이드바 구현
  client/src/components/Header.js
  client/src/components/Sidebar.js
Labels: [FE] 남궁태욱

#104 add : appspec.yml 파일 추가
  server/appspec.yml
Labels: [BE] 신지훈

#105 #61 #66 게시판 조회 시 별점 평균, 리뷰수, 판매자 이미지 기능 구현 완료
  server/src/main/java/team017/board/Controller/BoardController.java
  server/src/main/java/team017/board/Dto/BoardForSellerMyPageDto.java
  server/src/main/java/team017/board/Dto/BoardPatchDto.java
  server/src/main/java/team017/board/Dto/BoardPostDto.java
  server/src/main/java/team017/board/Dto/BoardResponseDto.java
  server/src/main/java/team017/board/Dto/BoardTotalResponseDto.java
  server/src/main/java/team017/board/Entity/Board.java
  server/src/main/java/team017/board/Mapper/BoardMapper.java
  server/src/main/java/team017/board/Repository/BoardRepository.java
  server/src/main/java/team017/board/Service/BoardService.java
  server/src/main/java/team017/comments/controller/CommentController.java
  server/src/main/java/team017/member/entity/SellerImage.java
  server/src/main/java/team017/review/repository/ReviewRepository.java
  server/src/main/java/team017/review/service/ReviewService.java
Labels: [BE] 신승현

#107 #69 feat : aop token 재발급 구현 및 자동로그인 시도
  server/build.gradle
  server/src/main/java/team017/ServerApplication.java
  server/src/main/java/team017/global/aop/ReissueToken.java
  server/src/main/java/team017/global/aop/SecurityAspect.java
  server/src/main/java/team017/member/controller/MemberController.java
  server/src/main/java/team017/member/dto/MemberDto.java
  server/src/main/java/team017/member/mapper/MemberMapper.java
  server/src/main/java/team017/security/config/SecurityConfig.java
  server/src/main/java/team017/security/controller/SecurityController.java
  server/src/main/java/team017/security/controller/SocialController.java
  server/src/main/java/team017/security/dto/LoginRequestDto.java
  server/src/main/java/team017/security/dto/LoginResponse.java
  server/src/main/java/team017/security/service/SecurityService.java
Labels: [BE] 가빈

#110 #21 #66 feat: Ord 기능구현 수정 + 판매 게시글 추가 기능 구현 완료
  server/src/main/java/team017/board/Dto/BoardForSellerMyPageDto.java
  server/src/main/java/team017/board/Dto/BoardResponseDto.java
  server/src/main/java/team017/board/Dto/BoardTotalResponseDto.java
  server/src/main/java/team017/board/Entity/Board.java
  server/src/main/java/team017/board/Repository/BoardRepository.java
  server/src/main/java/team017/board/Service/BoardService.java
  server/src/main/java/team017/ord/controller/OrdController.java
  server/src/main/java/team017/ord/dto/OrdPostDto.java
  server/src/main/java/team017/ord/dto/OrdResponseDto.java
  server/src/main/java/team017/ord/entity/Ord.java
  server/src/main/java/team017/ord/mapper/OrdMapper.java
  server/src/main/java/team017/ord/service/OrdService.java
Labels: [BE] 신승현

#111 #52 refactor: 코드 리팩터링 및 이미지 초기값 추가
  server/src/main/java/team017/member/controller/ClientController.java
  server/src/main/java/team017/member/controller/MemberController.java
  server/src/main/java/team017/member/controller/SocialController.java
  server/src/main/java/team017/member/dto/MemberDto.java
  server/src/main/java/team017/member/mapper/MemberMapper.java
  server/src/main/java/team017/member/service/ClientService.java
  server/src/main/java/team017/member/service/MemberService.java
  server/src/main/java/team017/member/service/SellerService.java
  server/src/main/java/team017/security/aop/SecurityAspect.java
  server/src/main/java/team017/security/jwt/TokenController.java
  server/src/main/java/team017/security/jwt/dto/LoginResponse.java
  server/src/main/java/team017/security/jwt/dto/TokenRequestDto.java
  server/src/main/java/team017/security/jwt/refresh/RefreshToken.java
  server/src/main/java/team017/security/jwt/service/SecurityService.java
  server/src/main/java/team017/security/oauth/dto/SocialPatchDto.java
Labels: [BE] 가빈

#112 Fix : yml 파일 수정
  server/src/main/java/team017/review/dto/ReviewPostDto.java
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
Labels: [BE] 신지훈

#115 Feat : 구매내역,판매내역조회 기능구현
  server/src/main/java/team017/board/Mapper/BoardMapper.java
  server/src/main/java/team017/board/Repository/BoardRepository.java
  server/src/main/java/team017/member/service/ClientService.java
  server/src/main/java/team017/ord/controller/MyPageController.java
  server/src/main/java/team017/ord/dto/OrdClientResponseDto.java
  server/src/main/java/team017/ord/dto/OrdSellerResponseDto.java
  server/src/main/java/team017/ord/dto/OrdSimpleResponseDto.java
  server/src/main/java/team017/ord/mapper/OrdMapper.java
  server/src/main/java/team017/ord/repository/OrdRepository.java
  server/src/main/java/team017/ord/service/OrdService.java
  server/src/main/java/team017/review/repository/ReviewRepository.java
Labels: [BE] 신지훈

#116 #108 fix: 엔티티 연관관계 수정
  server/src/main/java/team017/ord/entity/Ord.java
  server/src/main/java/team017/product/Entity/Product.java
  server/src/main/java/team017/security/jwt/JwtToken.java
Labels: [BE] 신승현, [BE] 가빈, [BE] 신지훈

#117 #66 feat: 주문,결제 실패 시 잔여 수량 변경 기능 구현
  server/src/main/java/team017/member/entity/Seller.java
  server/src/main/java/team017/ord/entity/Ord.java
  server/src/main/java/team017/payment/KakaoPayService.java
  server/src/main/java/team017/payment/ReadyResponseDto.java
Labels: [BE] 신승현

#119 #118 add seller log
  server/src/main/java/team017/member/controller/SellerController.java
  server/src/main/java/team017/member/service/MemberService.java
  server/src/main/java/team017/member/service/SellerService.java
Labels: [BE] 가빈

#122 #52 #120 feat: 현재 로그인 유저와 url 유저의 일치 판별 메서드 추가 및 컨트롤러 수정
  server/src/main/java/team017/member/controller/ClientController.java
  server/src/main/java/team017/member/controller/MemberController.java
  server/src/main/java/team017/member/mapper/MemberMapper.java
  server/src/main/java/team017/member/service/ClientService.java
  server/src/main/java/team017/member/service/SellerService.java
Labels: [BE] 가빈

#123 #52 fix: 수정
  server/src/main/java/team017/member/controller/ClientController.java
  server/src/main/java/team017/member/service/SellerService.java
Labels: [BE] 가빈

#125 feat: 카카오페이 redirect 시 파라미터 추가
  server/src/main/java/team017/board/Dto/BoardResponseDto.java
  server/src/main/java/team017/board/Mapper/BoardMapper.java
  server/src/main/java/team017/ord/controller/OrdController.java
  server/src/main/java/team017/ord/dto/OrdSellerResponseDto.java
  server/src/main/java/team017/payment/PaymentController.java
Labels: [BE] 신승현

#126 #124 feat: 카카오페이 결제 ec2 서버 통신 기능 구현 완료
  server/src/main/java/team017/payment/KakaoPayService.java
  server/src/main/java/team017/payment/PaymentController.java
Labels: [BE] 신승현

#128 #52 refactor & fix : add getBoard createAt, ModifiedAt and refactor Member
  server/src/main/java/team017/board/Dto/BoardForSellerMyPageDto.java
  server/src/main/java/team017/board/Mapper/BoardMapper.java
  server/src/main/java/team017/board/Repository/BoardRepository.java
  server/src/main/java/team017/member/controller/ClientController.java
  server/src/main/java/team017/member/controller/MemberController.java
  server/src/main/java/team017/member/controller/SellerController.java
  server/src/main/java/team017/member/controller/SocialController.java
  server/src/main/java/team017/member/entity/Member.java
  server/src/main/java/team017/member/mapper/MemberMapper.java
  server/src/main/java/team017/member/service/ClientService.java
  server/src/main/java/team017/member/service/MemberService.java
  server/src/main/java/team017/member/service/SellerService.java
  server/src/main/java/team017/ord/dto/OrdSellerResponseDto.java
  server/src/main/java/team017/security/config/SecurityConfig.java
  server/src/main/java/team017/security/config/WebMvcConfig.java
  server/src/main/java/team017/security/jwt/SecurityProvider.java
  server/src/main/java/team017/security/oauth/handler/OAuth2SuccessHandler.java
  server/src/main/java/team017/security/oauth/service/CustomOAuth2Service.java
  server/src/main/java/team017/security/oauth/service/KakaoService.java
Labels: [BE] 가빈

#130 [client]회원가입, 로그인, 생잔자마이페이지, 유저마이페이지
  client/.gitignore
  client/db.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/api/.gitkeep
  client/src/api/client.js
  client/src/api/login.js
  client/src/api/seller.js
  client/src/api/signup.js
  client/src/assets/images/f9bfadecab5b9feaae6ba584a7d18bc7-sticker.png
  client/src/assets/styles/GlobalStyles.js
  client/src/assets/styles/img/CropDetail.png
  client/src/assets/styles/img/farmer.jpeg
  client/src/assets/styles/img/lettuce.jpg
  client/src/components/Button.js
  client/src/components/CropBoard.js
  client/src/components/Footer.js
  client/src/components/Form.js
  client/src/components/Header.js
  client/src/components/Input.js
  client/src/components/Loader.js
  client/src/components/Pagination.js
  client/src/components/Paging.js
  client/src/components/Sidebar.js
  client/src/components/StarRate.js
  client/src/components/data.js
  client/src/features/axios.js
  client/src/features/cookie.js
  client/src/features/s3.js
  client/src/features/user/userSlice.js
  client/src/pages/CropsListPage.js
  client/src/pages/crops/CropInfoPage.js
  client/src/pages/sellers/SellerInfoPage.js
  client/src/pages/users/LoginPage.js
  client/src/pages/users/LogoutPage.js
  client/src/pages/users/MyPage.js
  client/src/pages/users/SignupPage.js
Labels: [FE] 김민성

#132 [client] 판매등록페이지 , 주문페이지
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/assets/styles/GlobalStyles.js
  client/src/assets/styles/fonts/fonts.js
  client/src/components/Header.js
  client/src/components/HomeLayout.js
  client/src/components/Sidebar.js
  client/src/components/buyform/ClientBuyform.js
  client/src/components/buyform/MultiStepBuyForm.js
  client/src/components/buyform/MultiStepBuyProgressBar.js
  client/src/components/buyform/PayForm.js
  client/src/components/sellerform/MultiStepForm.js
  client/src/components/sellerform/MultiStepProgressBar.js
  client/src/components/sellerform/SellerComplete.js
  client/src/components/sellerform/SellerContent.js
  client/src/components/sellerform/SellerPhoto.js
  client/src/components/sellerform/SellerPrice.js
  client/src/components/sellerform/SellerTitle.js
  client/src/features/pay/paySlice.js
  client/src/index.js
  client/src/pages/payments/BuyFoamPage.js
  client/src/pages/payments/BuyFormPage.js
  client/src/pages/payments/CompletePage.js
  client/src/pages/payments/FailPage.js
  client/src/pages/payments/PayPage.js
  client/src/pages/sellers/SellerPatchPage.js
  client/src/pages/sellers/SellerformPage.js
  client/src/pages/sellers/SellorPostPage.js
Labels: [FE] 남궁태욱

#134 #133 재고 상태 관련 주문, 게시판 수정
  server/src/main/generated/team017/board/Mapper/BoardMapperImpl.java
  server/src/main/generated/team017/member/mapper/MemberMapperImpl.java
  server/src/main/generated/team017/product/Mapper/ProductMapperImpl.java
  server/src/main/java/team017/board/Entity/Board.java
  server/src/main/java/team017/board/Mapper/BoardMapper.java
  server/src/main/java/team017/board/Repository/BoardRepository.java
  server/src/main/java/team017/board/Service/BoardService.java
  server/src/main/java/team017/global/Exception/ExceptionCode.java
  server/src/main/java/team017/ord/service/OrdService.java
  server/src/main/java/team017/payment/KakaoPayService.java
  server/src/main/java/team017/product/Entity/Product.java
Labels: [BE] 신승현

#136 Refactor : 각 요청에 토큰 검증
  server/src/main/java/team017/comments/controller/CommentController.java
  server/src/main/java/team017/comments/service/CommentService.java
  server/src/main/java/team017/image/FileUploadController.java
  server/src/main/java/team017/member/dto/SellerPatchDto.java
  server/src/main/java/team017/ord/controller/MyPageController.java
  server/src/main/java/team017/ord/controller/OrdController.java
  server/src/main/java/team017/ord/dto/OrdClientResponseDto.java
  server/src/main/java/team017/ord/dto/OrdPostDto.java
  server/src/main/java/team017/ord/dto/OrdSellerResponseDto.java
  server/src/main/java/team017/ord/entity/Ord.java
  server/src/main/java/team017/ord/mapper/OrdMapper.java
  server/src/main/java/team017/review/controller/ReviewController.java
  server/src/main/java/team017/review/dto/ReviewPatchDto.java
  server/src/main/java/team017/review/mapper/ReviewMapper.java
  server/src/main/java/team017/review/service/ReviewService.java
  server/src/main/java/team017/security/jwt/SecurityProvider.java
Labels: [BE] 신지훈

#137 feat: sidebar 수정, 주문작성페이지 유저 데이터 불러오기
  client/package-lock.json
  client/src/components/Header.js
  client/src/components/Sidebar.js
  client/src/components/buyform/ClientBuyform.js
  client/src/pages/payments/BuyFormPage.js
  client/src/pages/sellers/SellerformPage.js
Labels: [FE] 남궁태욱

#139 #133 feat: 재고 관련 주문 상태 수정
  server/src/main/java/team017/ord/controller/OrdController.java
  server/src/main/java/team017/ord/service/OrdService.java
  server/src/main/java/team017/product/Entity/Product.java
  server/src/main/java/team017/product/Service/ProductService.java
Labels: [BE] 신승현

#140 #133 fix: transcational controller 수정
  server/src/main/java/team017/ord/service/OrdService.java
Labels: [BE] 신승현

#141 #52 fix: token and config 관련 수정
  server/src/main/java/team017/member/controller/SellerController.java
  server/src/main/java/team017/security/config/SecurityConfig.java
  server/src/main/java/team017/security/jwt/SecurityProvider.java
  server/src/main/java/team017/security/oauth/service/KakaoService.java
Labels: [BE] 가빈

#143 feat: 소셜로그인(카카오) 구현, 생잔자 마이페이지, 구매자 마이페이지 목록 수정
  client/src/api/seller.js
  client/src/assets/images/kakao_login_medium_wide.png
  client/src/components/Button.js
  client/src/components/buyform/ClientBuyform.js
  client/src/pages/payments/BuyFormPage.js
  client/src/pages/sellers/SellerInfoPage.js
  client/src/pages/sellers/SellerformPage.js
  client/src/pages/users/LoginPage.js
  client/src/pages/users/MyPage.js
Labels: [FE] 김민성

#144 [client] 구매, 판매 페이지 충돌 수정
  client/src/pages/payments/BuyFormPage.js
  client/src/pages/sellers/SellerformPage.js
Labels: [FE] 남궁태욱

#145 #11 #52 ExceptionCode, Board 코드 리펙토링
  server/src/main/java/team017/board/Controller/BoardController.java
  server/src/main/java/team017/board/Dto/BoardPostDto.java
  server/src/main/java/team017/board/Dto/BoardResponseDto.java
  server/src/main/java/team017/board/Entity/Board.java
  server/src/main/java/team017/board/Mapper/BoardMapper.java
  server/src/main/java/team017/board/Repository/BoardRepository.java
  server/src/main/java/team017/board/Service/BoardService.java
  server/src/main/java/team017/global/Exception/ExceptionCode.java
  server/src/main/java/team017/ord/service/OrdService.java
Labels: [BE] 신승현

#146 [client] #77 feat: review,comment delete 구현, 날짜 출력변경,수정버튼연결
  client/package-lock.json
  client/src/components/Comment.js
  client/src/components/CommentPaging.js
  client/src/components/CropInfoElement.js
  client/src/components/Review.js
  client/src/components/StarRate.js
  client/src/components/TimeCheck.js
  client/src/pages/crops/CropInfoPage.js
Labels: [FE] 권수현

#149 #21 fix: Ord mapper 수정
  server/src/main/java/team017/ord/entity/Ord.java
  server/src/main/java/team017/ord/mapper/OrdMapper.java
  server/src/main/java/team017/ord/service/OrdService.java
Labels: [BE] 신승현

#150 #118 add: add log to find error
  server/src/main/java/team017/member/controller/SocialController.java
  server/src/main/java/team017/security/oauth/service/KakaoService.java
Labels: [BE] 가빈

#151 [client] fix:날짜출력수정
  client/src/components/Comment.js
  client/src/components/CropInfoElement.js
  client/src/components/Review.js
  client/src/components/Viewer.js
  client/src/pages/CropsListPage.js
  client/src/pages/crops/CropInfoPage.js
Labels: [FE] 권수현

#152 Fix : ServerTime Asia로 변경
  server/src/main/java/team017/ord/service/OrdService.java
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
Labels: [BE] 신지훈

#153 #69 fix: kakao login
  server/build.gradle
  server/src/main/java/team017/member/controller/SocialController.java
  server/src/main/java/team017/security/oauth/service/KakaoService.java
Labels: [BE] 가빈

#156 feat: 마이페이지 날짜 추가 , 수정
  client/src/api/client.js
  client/src/api/login.js
  client/src/api/seller.js
  client/src/components/Input.js
  client/src/features/cookie.js
  client/src/features/s3.js
  client/src/pages/users/MyPage.js
Labels: [FE] 김민성

#157 [client] 수정페이지구현
  client/src/App.js
  client/src/components/CropInfoElement.js
  client/src/components/HomeNav.js
  client/src/components/HomeVisual.js
  client/src/components/buyform/PayForm.js
  client/src/components/sellerform/SellerContent.js
  client/src/components/sellerform/SellerTitle.js
  client/src/pages/sellers/SellerPatchPage.js
  client/src/pages/sellers/SellerformPage.js
Labels: [FE] 남궁태욱
